add Chinese (Simple)
OpenRailwayMap/OpenRailwayMap pull request #691
Opened 2020-09-02 22:59 UTC by qa003qa003

add Chinese (Simple)

2020-09-03 06:23 UTC, DerDakon requested changes
Please drop the commit that introduces locals/messages.po as this is just a duplicate. Also please add an entry to api/config.php so it will be selectable. At the end please squash everything together in a single commit.

2021-07-24 10:03 UTC, myzhang1029 requested changes
I've proofread most of the English-to-SC translations, and I kindly suggest some changes to be considered.

2021-07-24 10:03 UTC, myzhang1029 commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr ""
`"列车保护系统"`.

2021-07-24 10:03 UTC, myzhang1029 commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr ""
`"接触网"`.

2021-07-24 10:03 UTC, myzhang1029 commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr ""
`"电气化在建"`.

2021-07-24 10:03 UTC, myzhang1029 commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr ""
`"芬兰"`.

2021-07-24 10:31 UTC, DerDakon commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr "％s前"
Yes, absolutely. Nice catch, I didn't spot this.

2021-08-21 07:04 UTC, DerDakon commented
Fixes: #735

2021-09-18 15:10 UTC, Nakaner commented on locales/zh_CN/LC_MESSAGES/messages.po
> +msgstr "％s前"
Yes, the `%` is required for string formatting.

2021-09-21 13:27 UTC, Nakaner commented
Closed in favour of #740

2021-09-21 13:27 UTC, closed without merging