fix getPermalinkUrl() to not include lang=null param
OpenRailwayMap/OpenRailwayMap pull request #713
Opened 2021-02-25 20:19 UTC by mmoll

closes GH-712

2021-02-26 14:40 UTC, DerDakon commented on js/functions.js
> +	if(lang != null) {
what about something like this instead:

```js
if (lang === null) { lang = params['lang']; }
if (lang !== null) { url += &lang="+lang; }
```

2021-02-26 14:53 UTC, mmoll commented on js/functions.js
> +	if(lang != null) {
✅

2021-02-26 20:18 UTC, Nakaner requested changes
It is `lang=undefined` instead of `lang=null` now.

2021-02-26 21:09 UTC, mmoll commented
Should be fixed now.

2021-02-26 21:44 UTC, DerDakon commented
You can use the same indentation style like the surrounding code…

2021-02-27 07:32 UTC, DerDakon approved these changes

2021-02-27 19:07 UTC, merged

2021-02-27 19:10 UTC, Nakaner commented
The changes were deployed a few minutes ago.