Added Dutch translations
OpenRailwayMap/OpenRailwayMap pull request #775
Opened 2022-04-04 18:37 UTC by STemplar

2022-04-04 19:09 UTC, DerDakon commented
@JJJWegdam could you review this?

2022-04-06 18:51 UTC, JJJWegdam requested changes
I made some translations more specific and simplified some others. Are you okay with implementing those?

Signal ~~Signaal~~ Sein
speed only given for one direction ~~Snelheid in een richting~~ snelheid alleen bekend voor één richting
main track, service track ~~hoofdspoor, onderhoudsspoor~~ hoofdbaan, zijspoor
Search milestone ~~Zoek mijlpaal~~ Zoek kilometrering
Station code ~~Stationscode~~ Stationafkorting
Line operator ~~Lijn exploitant~~ Exploitant
Operator ~~Spoorwegmaatschappij~~ Beheerder
Spur junction ~~Raccordement aansluiting~~ Spooraansluiting
signals ~~signalen~~ seinen
Operating Sites ~~Dienstregelingspunten~~ Dienstregelmeetpunten
Hp-Lichthauptsignal ohne Angabe der Signalzustände ~~Hp hoofdlichtsein zonder indicatie van de signaalstatus~~ Hp-hoofdlichtsein zonder indicatie van de seintoestand
Lf 7 Geschwindigkeitssignal ~~Lf 7 Snelheidssignaal~~ Lf7-snelheidssein
El 5 \"Bügel an\"-Signal" ~~El 5 Raise pantograph signal~~ El5-\"Stroomafnemers op\"-sein
So 106 Kreuztafel ~~So 106 Kreuztafel~~ So106-kruisbord
Hp-Formhauptsignal ohne Angabe der Signalzustände ~~Hp-Hoofdarmsein zonder indicatie van de signaalstatus~~ Hp-Hoofdarmsein zonder indicatie van de seintoestand
El 4 \"Bügel ab\"-Signal ~~El 4 Lower pantograph signal~~ El4-\"Stroomafnemers neer\"-sein

2022-04-28 11:55 UTC, Nakaner commented
@JJJWegdam I commited your suggested changes and pushed them to the branch.

2022-07-02 19:44 UTC, Nakaner approved these changes

2022-07-03 09:21 UTC, merged