Leaflet 1.9
OpenRailwayMap/OpenRailwayMap pull request #815
Opened 2023-01-04 21:32 UTC by hiddewie

Split off from https://github.com/OpenRailwayMap/OpenRailwayMap/pull/814, see https://github.com/OpenRailwayMap/OpenRailwayMap/pull/814/files#r1059973240

Changes in this PR:
- Use the .zip distribution of the Leaflet library (the Github archive does not contain the javascript files in built form)
- Update the location button icon because the style has changed a bit in the new Leaflet version, and otherwise the buttons overlap and look bad.
- The Javascript source map is added because it is bundled and browsers request it.

2023-01-04 21:33 UTC, hiddewie commented on Makefile
> +	wget -O download/leaflet.zip https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/v$(DEP_LEAFLET_VERSION)/leaflet.zip
The URL https://github.com/Leaflet/Leaflet/releases/download/v1.9.3/leaflet.zip also works by the way, so we can choose if the Github or Amazon CDN is preferred.

2023-02-25 17:34 UTC, Nakaner requested changes
If I fix your makefile mistake, I get following Javascript error:

```
Uncaught TypeError: this._layer is undefined
    _tileOnLoad L.TileLayer.Grayscale.js:25
    o DomEvent.js:108
    ke DomEvent.js:135
    S DomEvent.js:34
    createTile TileLayer.js:150
    _addTile GridLayer.js:810
    _update GridLayer.js:713
    _setView GridLayer.js:574
    _resetView GridLayer.js:530
    onAdd GridLayer.js:162
    _layerAdd Layer.js:114
    fire Events.js:195
    _resetView Map.js:1198
    setView Map.js:206
    setPosition startposition.js:28
    Startposition startposition.js:81
    createMap bitmap-map.js:72
    onload functions.js:102
    getRequest functions.js:98
    createMap bitmap-map.js:25
    onload (index):1
20 L.TileLayer.Grayscale.js:25:7
    _tileOnLoad L.TileLayer.Grayscale.js:25
    _tileOnLoad self-hosted:1518
    o DomEvent.js:108
    (Async: EventListener.handleEvent)
    ke DomEvent.js:135
    S DomEvent.js:34
    createTile TileLayer.js:150
    _addTile GridLayer.js:810
    _update GridLayer.js:713
    _setView GridLayer.js:574
    _resetView GridLayer.js:530
    onAdd GridLayer.js:162
    _layerAdd Layer.js:114
    fire Events.js:195
    _resetView Map.js:1198
    setView Map.js:206
    setPosition startposition.js:28
    Startposition startposition.js:81
    createMap bitmap-map.js:72
    onload functions.js:102
    (Async: EventHandlerNonNull)
    getRequest functions.js:98
    createMap bitmap-map.js:25
    onload (index):1
```

2023-02-25 17:34 UTC, Nakaner commented on Makefile
>  download/leaflet-$(DEP_LEAFLET_VERSION).tar.gz:
You have to change the file name suffix in the make target because the "produced" file ends with ".zip".

2023-05-29 18:45 UTC, hiddewie commented
@Nakaner 

>  I get following Javascript error:

I can reproduce the issue. It seems the custom grayscale layer is not compatible with the newer Leaflet version.

So I will close this PR, and the original PR https://github.com/OpenRailwayMap/OpenRailwayMap/pull/814 is still open for discussion so the entire change can be merged at once..

2023-05-29 18:45 UTC, closed without merging