Remove API code, add references to other GitHub repositories
OpenRailwayMap/OpenRailwayMap pull request #857
Opened 2023-10-15 12:54 UTC by Nakaner

We have switched to the new API. Threfore the old code can be deleted.

2023-10-15 14:02 UTC, DerDakon commented
You need to update INSTALL.md as well I think as it talks about the APi.

2023-10-17 17:54 UTC, DerDakon requested changes

2023-10-17 17:54 UTC, DerDakon commented on INSTALL.md
> +$ rm -fr osm2pgsql-build osm2pgsql-1.9.2 1.9.2.tar.gz
I would omit the `rm` here as well as in other places. Everyone should be able to clean that up alone if it is relevant.

2023-10-17 17:54 UTC, DerDakon commented on INSTALL.md
> +for STYLE in standard maxspeed signals electrification gauge ; do
put the mkdir in the loop

2024-06-01 10:12 UTC, merged

2024-06-02 16:15 UTC, vhscom commented on INSTALL.md
> +cd /srv/OpenRailwayMap-setup/ansible/role/tileserver/files/scripts
Thanks for updating this. Had me scratching my head last week. Eventually figured it out. Now we won't need to.

2024-06-02 16:15 UTC, vhscom commented on INSTALL.md
> +cd /srv/OpenRailwayMap-setup/ansible/role/tileserver/files/scripts
Thanks for fixing this. Had me scratching my head last week.